version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.8.0
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/tmdb_db
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW_UID: 50000
    AIRFLOW__WEBSERVER__SECRET_KEY: 'local_dev_key'
    AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
    AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
  volumes:
    - ./dags:/opt/airflow/dags
    - ./pipeline:/opt/airflow/pipeline
    - ./database:/opt/airflow/database
    - ./data:/opt/airflow/data
    - ./requirements.txt:/requirements.txt
  depends_on:
    postgres:
      condition: service_healthy
  env_file:
    - .env

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: bash -c "pip install -r /requirements.txt && airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@admin.com"
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "pip install -r /requirements.txt &&
               airflow webserver"
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "pip install -r /requirements.txt &&
               airflow scheduler"
    restart: always

volumes:
  postgres_data: